from .stgy import Stgy
from .stgyBuy import StgyBuy
from .stgyBuyNaive import StgyBuyNaive
from .stgyBuy4MA import StgyBuy4MA
from .stgyBuyNewHigh import StgyBuyNewHigh
from .stgy_breakout import Stgy_BO
from .stgy_buyAndHold import Stgy_BAH
from .stgy_ma import Stgy_MA
from .stgy_cupHandle import Stgy_CH